### ISSUE TITLE
SPI transmission and reception are not functioning as expected for stm32g0c1ret3 controller

### ISSUE THREAD

**Issue by RiyaKori-eaton** [zephyrproject-rtos/zephyr#86698]
**Describe the bug**
 NA

**To Reproduce**
1.  The pin configurations which was supported by our microcontroller has been done .
2. Necessary files have been updated, including the DTS file, overlay file, prj.conf file, and CMakeLists.txt.
3. The build process has been completed, and the firmware has been successfully flashed onto the microcontroller.

**Expected behavior**
  In SPI (Serial Peripheral Interface) communication, if values are transmitted via the transmission buffer, corresponding values should be received in the receiver buffer. This is a fundamental aspect of SPI's full-duplex communication capability.

**Impact**
 showstopper

**Logs and console output**

**In Zephyr 3.6.0**
we checked SPI clock on nucleo-g071rb and nucleo-g474re
In  nucleo-g071rb we are not able to see sclk waveform and nucleo-g474re series its working fine
 
below screenshot is for nucleo-g474re

![Image](https://github.com/user-attachments/assets/aaf9d3fb-fbbd-41cc-a6fa-873b00c0933c)

**In Zephyr 4.0.0**
we checked SPI clock on nucleo-g071rb and nucleo-g474re
In  nucleo-g071rb we are not able to see sclk waveform and nucleo-g474re series its working fine
For nucleo-g071rb we observed same issue there is no activity on sclk

![Image](https://github.com/user-attachments/assets/22a989d6-41a1-426f-a732-68a74a7ac97e)

for nucleo-g474re sclk we are able to see the waveform

![Image](https://github.com/user-attachments/assets/e5f2dd6b-6ad2-46dd-a048-fb6e082e536c)

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)  
 - Windows
 - Toolchain (e.g Zephyr SDK, ...)
 - Zephyr 3.6.0
 - Commit SHA or Version used
 
![Image](https://github.com/user-attachments/assets/8af9ab37-59d7-47b8-85ca-49ca6d86b8dc)

![Image](https://github.com/user-attachments/assets/3cd57c98-eca4-4d4e-8da3-f12cd264c2f2)
![Image](https://github.com/user-attachments/assets/6c9748b8-03dd-4f5d-ae95-0ad22ccab594)
![Image](https://github.com/user-attachments/assets/50534808-0afc-4aa1-8eb1-daed9c5aa84d)

 - NA

**Additional context**
[](url) @AmolMeshram-eaton
@bhardadinesh-eaton

**Comment by realhonbo** [comment]
I thought it maybe a old bug of hardware nss caused, it occurred in stm32f1xx and stm32f4xx, and fixed in stm32h7xx:
pb-0 is the hardware nss of alternate spi1, Even though you choose it to soft-nss, may dtc processed it to hard-nss? Could you have a try to change a cs pin?

<img src="https://github.com/user-attachments/assets/e3a4f172-288c-4728-942a-4aa12cdf3574" width="70%">

**Comment by RiyaKori-eaton** [comment]
According to the Zephyr documentation, when using spi_transceive() and providing a valid spi_cs_control structure in the spi_config (via the .cs member), the chip select (CS) pin should be automatically asserted (set low) before the transfer and de-asserted (set high) after the transfer. However, if the CS pin is not being set and reset automatically during the SPI transaction, would manually controlling the CS pin resolve this issue?

Additionally, as previously mentioned, the SPI clock signal is not visible for G0 series  during the operation. Could you provide possible reasons for the absence of the clock signal in this scenario? @realhonbo @JarmouniA @erwango

**Comment by JarmouniA** [comment]
@RiyaKori-eaton Zephyr v3.6.0 is no longer supported, try reproducing the issue on v3.7.1 or later.

**Comment by RiyaKori-eaton** [comment]
We have also attempted this on Zephyr v4.0.0, but the clock signal is still not observed. Please refer to the attached screenshots for further details @JarmouniA

**Comment by gautierg-st** [comment]
Hi @RiyaKori-eaton,
I've tried to reproduce your issue with a Nucleo G071RB and a Nucleo G0B1RE, in v3.7.0, v4.0.0 and current main, with default SPI pins and your own, with CS as GPIO or as HW NSS, but in all cases, I see all signals and tests/drivers/spi/spi_loopback is successful.

Do you have a particular setup that could explain your issue?
