### ISSUE TITLE
stm32h573i_dk and similar: MCUBoot with external flash not able to update image

### ISSUE THREAD

**Issue by Jowllel** [zephyrproject-rtos/zephyr#92883]
### Describe the bug

When trying to run the "boards/st/hello_world_xip" sample from https://github.com/zephyrproject-rtos/zephyr/pull/88579 (or the upcoming Zephyr release) with the following lines added to prj.conf:
````
CONFIG_FLASH=y
CONFIG_LOG=y
CONFIG_FLASH_LOG_LEVEL_ERR=y
````
The external flash initialisation fails with the following log message: "flash_stm32_xspi: XSPI Init failed"

However, the flash API is used to update or manage the MCUBoot images. (E.g. Flash Image API, MCUboot image contol API, IMG_MANAGER). So if the external flash isn't initialised, the image can't be updated or swapped.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Use https://github.com/zephyrproject-rtos/zephyr/pull/88579 or the upcoming Zephyr release, if the PR is already merged into main.
2. Add the following lines to prj.conf of the "boards/st/hello_world_xip" sample
````
CONFIG_FLASH=y
CONFIG_LOG=y
CONFIG_FLASH_LOG_LEVEL_ERR=y
````
3. build the sample: ```west build -p -b stm32h573i_dk samples/boards/st/hello_world_xip/ --sysbuild --   -DSB_CONFIG_BOOTLOADER_MCUBOOT=y```
4. flash the sample to a stm32h573i_dk board: ```west flash```
5. Open UART Port of the ST-Link and the error should appear in the log.

### Relevant log output

```shell
flash_stm32_xspi: XSPI Init failed
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- OS: Windows
- Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/88579

**Comment by Jowllel** [comment]
@FRASTM

**Comment by erwango** [comment]
I don't think it is appropriate to raise issue on non merged PR, specially if you're adding your own configuration on top.
I understand this is a requested feature for you, but this isn't a bug from our perspective (if anyone does the same we'll be quickly overwhelmed by issues).
Please convert to discussion to follow up on this point.

**Comment by Jowllel** [comment]
I just thought that I'd create a new Issue, because the supporters from the mentioned PR said they wouldn't fix it. So nothing about the flash API Initialisation should change in the PR. 
I'm sorry if I'm a bit stressful about this. But I have a project deadline in 2 weeks, where our mainboard need an Image which can be remotely updated, because their getting deployed in the country.
So if there's any workaround or similar I'd be happy to. I just need a remotely updateable Image.
Or should we wait with the Issue until the PR is merged an then proceed? Maybe with a quick-fix until then.
But, however. Thanks a lot for your help.

**Comment by FRASTM** [comment]
What I see with that usecase is : 
when starting the execution on the xspi NOR flash (in XiP, after mcuboot) the flash_stm32_xspi driver is calling the flash_stm32_xspi_init. This function should retrun without trying to re-init the xspi where we are executing on
That's the prupose of the check (if stm32_xspi_is_memorymap at line https://github.com/zephyrproject-rtos/zephyr/blob/732a3a5c66553969ea01bacec19e2820b9d6b2e2/drivers/flash/flash_stm32_xspi.c#L2050


1. The `#ifdef CONFIG_STM32_MEMMAP`  must be replaced by   `#ifdef CONFIG_FLASH_STM32_XSPI_XIP`
2. The check on the clock_control_get_status returns CLOCK_CONTROL_STATUS_UNKNOWN. I would propose to replace with 	

```
if (clock_control_get_status(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
				     (clock_control_subsys_t) &dev_cfg->pclken)
				     != CLOCK_CONTROL_STATUS_OFF) {

```

**Comment by FRASTM** [comment]
If you prefer,  I can now add this change in a new commit on the original PR.

**Comment by Jowllel** [comment]
That would be great, yes.
Thanks a lot

**Comment by FRASTM** [comment]
> That would be great, yes. Thanks a lot

done in the https://github.com/zephyrproject-rtos/zephyr/pull/88579

**Comment by Jowllel** [comment]
Okay. The Flash init error disappeared now, but it still seems that there's a problem with the external flash, because everytime when the flash is accessed there's a bus fault. (Tested with the MCUboot command in shell)

LOG:
```
*** Booting MCUboot v2.2.0-59-g6e488501298c ***
*** Using Zephyr OS build v4.2.0-rc1-269-gbba24ce6b54a ***
I: Starting bootloader
I: Primary image: magic=bad, swap_type=0x0, copy_done=0x2, image_ok=0x2
I: Secondary image: magic=bad, swap_type=0x0, copy_done=0x2, image_ok=0x2
I: Boot source: none
I: Image index: 0, Swap type: none
I: Bootloader chainload address offset: 0x0
I: Image version: v0.0.0
I: Jumping to the first image slot
Hello World! from external flash  stm32h573i_dk
--> PC at 0x90000ae6

*** Booting Zephyr OS build v4.2.0-rc1-269-gbba24ce6b54a ***
uart:~$ mcuboot 
[00:00:02.723,000] <err> os: ***** BUS FAULT *****
[00:00:02.723,000] <err> os:   Precise data bus error
[00:00:02.723,000] <err> os:   BFAR Address: 0x0
[00:00:02.723,000] <err> os: r0/a1:  0x00000000  r1/a2:  0x26f49876  r2/a3:  0x0000000f
[00:00:02.723,000] <err> os: r3/a4:  0x00000000 r12/ip:  0x00005dc0 r14/lr:  0x9000a0e5
[00:00:02.723,000] <err> os:  xpsr:  0x61000000
[00:00:02.723,000] <err> os: Faulting instruction address (r15/pc): 0x9000e768
[00:00:02.723,000] <err> os: >>> ZEPHYR FATAL ERROR 25: Unknown error on CPU 0
[00:00:02.724,000] <err> os: Current thread: 0x20000770 (shell_uart)
[00:00:02.799,000] <err> os: Halting system

```

With the following prj.conf: (To enable the mcuboot command):
```
#CONFIG_XIP=y

CONFIG_FLASH=y
CONFIG_LOG=y
CONFIG_FLASH_LOG_LEVEL_ERR=y
CONFIG_SHELL=y
CONFIG_FLASH_SHELL=y
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SHELL=y
CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_FLASH_MAP=y
```

**Comment by FRASTM** [comment]
I see this bus fault happening with the samples/sysbuild/with_mcuboot/ --sysbuild 
When the application ('with_mcuboot') is executing in place in the external flash, this mcuboot shell is accessing the external flash for reading during its own execution in the external flash. Because the CONFIG_STM32_MEMMAP is not set by this mcuboot shell, the flash_stm32_xspi_read tries to send command to itself: that cannot work properly.

1) replace 
`#if CONFIG_STM32_MEMMAP`
with
`#if defined(CONFIG_STM32_MEMMAP) || defined(CONFIG_STM32_APP_IN_EXT_FLASH)
`
2) there is problem with xspi_lock_thread during read operation
I guess it locks the thread it is executing. Removing : 
```

*** Booting Zephyr OS build v4.2.0-677-gff886c78f2af ***
Address of sample 0x90000000                                                                                         
Hello sysbuild with mcuboot! stm32h573i_dk                                                                           
uart:~$ mcuboot                                                                                                      
swap type: none                                                                                                      
confirmed: 1                                                                                                         
                                                                                                                     
primary area (2):                                                                                                    
  version: 0.0.0+0                                                                                                   
  image size: 78008                                                                                                  
  magic: unset                                                                                                       
  swap type: none                                                                                                    
  copy done: unset                                                                                                   
  image ok: unset                                                                                                    
                                                                                                                     
failed to read secondary area (3) header: -5                                                                         
[00:00:04.067,000] <inf> mcuboot_util: Image index: 0, Swap type: none                                               
uart:~$ 
```

**Comment by Jowllel** [comment]
Hi
The flash read seems to be fixed now, but I still have problems with flash write/erase. (used to update the image on the external flash)

E.g. If you try to erase the secondary image (partition id 3 from ```flash_map list``` command) with ```mcuboot erase 3``` you'll get the following error: 
```
***** BUS FAULT *****
  Precise data bus error
  BFAR Address: 0x0
r0/a1:  0x00000000  r1/a2:  0x76c5155e  r2/a3:  0x0000000f
r3/a4:  0x00000000 r12/ip:  0x00005dc0 r14/lr:  0x90007ed1
 xpsr:  0x61000000
Faulting instruction address (r15/pc): 0x9000bee2
```

or if you try to manually write bytes into the secondary unused image using this command: ```flash write ospi-nor-flash@0 0x1000000 55``` you'll get the same bus fault.

or the same with the  ```flash_img_buffered_write``` with flush set to true, used to update the mcuboot image from code.

**Comment by Jowllel** [comment]
@kartben What's with the flash write? Still not able to update the image as mentioned in: https://github.com/zephyrproject-rtos/zephyr/issues/92883#issuecomment-3244388936

**Comment by JarmouniA** [comment]
> Hi The flash read seems to be fixed now, but I still have problems with flash write/erase. (used to update the image on the external flash)

_"Note that writing or erasing the external flash being executed is not possible during the execution on the external flash."_ 
from https://github.com/zephyrproject-rtos/zephyr/pull/93762#issue-3269350830

You will have to use an MCUboot mode that executes in RAM, and implement this change https://github.com/zephyrproject-rtos/zephyr/pull/93762#discussion_r2239387492

**Comment by Jowllel** [comment]
So there isn't an option to update the secondary image while the primary image is running in XIP? I'm a bit confused because I thought this should be possible. How else should all the OTA samples work? The RAM usually doesn't have enough space to store a whole image...

**Comment by JarmouniA** [comment]
> So there isn't an option to update the secondary image while the primary image is running in XIP? I'm a bit confused because I thought this should be possible.

It is possible, but will require:
- modifying the xSPI Flash driver to allow for writing in MemMapped mode, and to account for the different MCUboot modes and the enabling of `CONFIG_STM32_MEMMAP` on app side,
- targeted code relocation to RAM for the Flash stack & image update routines...

Take a look at #88773 which implements initial support for writing in MemMapped mode, but without accounting for the XiP in Ext Flash usecase.

**Comment by Jowllel** [comment]
Would this be a feature that could be implemented for the next zephyr release. I think it would be quite helpful for bigger applications running remote microcontrollers, especially STM32s, as they don't have that much flash and are often used with external flashes.

**Comment by FRASTM** [comment]
closed as [#93762](https://github.com/zephyrproject-rtos/zephyr/pull/93762) is now merged

**Comment by Jowllel** [comment]
Well. I'm still not able to update the image on external Flashes with STM32, because I can't write to the flash with XIP and memmap activated. Should i open a new Issue for this problem?

**Comment by Jowllel** [comment]
@FRASTM  ?

**Comment by JarmouniA** [comment]
Issue partially fixed https://github.com/zephyrproject-rtos/zephyr/issues/92883#issuecomment-3244483225

**Comment by FRASTM** [comment]
> Well. I'm still not able to update the image on external Flashes with STM32, because I can't write to the flash with XIP and memmap activated. Should i open a new Issue for this problem?

When the MemoryMapped mode is enabled (CONFIG_STM32_MEMMAP=y), writing to the external flash is possible in indirect mode (MemoryMapped mode is aborted), which is not compatible with the XIP = reading/executing on this flash: XIP is with CONFIG_STM32_MEMMAP. In other words, you cannot write to an external flash while you are executing on this external flash  (this is a kind of _ReadWhileWrite_ which is not supported).

**Comment by Jowllel** [comment]
Ah Okay
Do you have any recommendations on how to solve this problem? Because the Flash size on STM32s only goes up to 2/4MB, which isn't sufficient for my application. For it to be updatable, I need double the Flash size than the Firmware Image size. That's why I decided to use an external flash for the images, as many nucleo boards also do. But now the images can't be updated when they're also running in the external flash? Are there any alternatives?

Isn't this a standard application for the external Flash on an STM32? OTA Updates and the firmware running from the external flash?

**Comment by JarmouniA** [comment]
In general, in order to be able to switch off memory-mapping temporarily when executing in external Flash (to write to ext Flash storage partition in normal mode for ex., since writing in MemMapped mode is not supported by all SoCs, and not implemented currently for the ones supporting it #88773), the code of ext flash driver, the xSPI controller driver, and all their direct HAL dependencies should be relocated to RAM by default, similar to what NXP is doing
https://github.com/zephyrproject-rtos/zephyr/blob/c9b01e8257dbe54e0f3b765f89fb69ffbafa201f/drivers/flash/CMakeLists.txt#L111
Although that would prevent users from using LTO.

An alternative would be to use RAM Functions for Zephyr drivers, similar to
https://github.com/zephyrproject-rtos/zephyr/blob/1028fc27b3d9d7848034da1e693c5e140f14d89b/drivers/flash/flash_sf32lb_mpi_qspi_nor.c#L503
and Zephyr Relocation for HAL drivers libraries.
