### ISSUE TITLE
STM32 USB Regression

### ISSUE THREAD

**Issue by ExtremeGTX** [zephyrproject-rtos/zephyr#94916]
### Describe the bug

After updating to latest main zephyrproject-rtos/zephyr@617b71bc174be034b6b910792ea922c47b568068 from zephyrproject-rtos/zephyr@d84348fbd1a17824b6345de814f16bba0c6bc67d USB is not working any more on STM32F769i_disco

### Regression

- [x] This is a regression.

### Steps to reproduce

1. `west build -b stm32f769i_disco ./samples/subsys/usb/cdc_acm/ `
2.  `copy ./build/zephyr/zephyr.bin <STLink MSC Partition>`

### Relevant log output

```shell
*** Booting Zephyr OS build v4.2.0-2290-g617b71bc174b ***
[00:00:00.010,000] <inf> cdc_acm_echo: USB device support enabled
[00:00:00.010,000] <inf> cdc_acm_echo: Wait for DTR
[00:00:00.016,000] <inf> cdc_acm_echo: USBD message: Device suspended
[00:00:00.130,000] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:00.167,000] <err> usbd_core: unrecoverable error -22, ep 0x00, buf 0x20023bf8
[00:00:00.167,000] <inf> cdc_acm_echo: USBD message: Stack error
[00:00:05.689,000] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:05.795,000] <err> usbd_core: unrecoverable error -22, ep 0x00, buf 0x20023c1c
[00:00:05.795,000] <inf> cdc_acm_echo: USBD message: Stack error
[00:00:11.316,000] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:11.419,000] <err> usbd_core: unrecoverable error -22, ep 0x00, buf 0x20023bf8
[00:00:11.419,000] <inf> cdc_acm_echo: USBD message: Stack error
[00:00:16.936,000] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:17.039,000] <err> usbd_core: unrecoverable error -22, ep 0x00, buf 0x20023c1c
[00:00:17.039,000] <inf> cdc_acm_echo: USBD message: Stack error
[00:00:22.046,000] <inf> cdc_acm_echo: USBD message: Device suspended
```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

- OS:  Ubuntu 24.04.2 LTS
- Toolchain: zephyr 0.17.0
- Commit SHA: 617b71bc174be034b6b910792ea922c47b568068 

### Additional Context

Same sample is working on Raspberry Pi Pico W

Edit: Add old working commit

**Comment by erwango** [comment]
@ExtremeGTX Can you provide the version you're coming from ?

**Comment by ExtremeGTX** [comment]
@erwango coming from commit zephyrproject-rtos/zephyr@d84348fbd1a17824b6345de814f16bba0c6bc67d

**Comment by erwango** [comment]
> [@erwango](https://github.com/erwango) coming from commit [d84348f](https://github.com/zephyrproject-rtos/zephyr/commit/d84348fbd1a17824b6345de814f16bba0c6bc67d)

@marwaiehm-st FYI

**Comment by marwaiehm-st** [comment]
Hi @ExtremeGTX,

I have identified that the regression was introduced by commit [cd17871](https://github.com/zephyrproject-rtos/zephyr/commit/cd17871cfe3ae3888569c6989a536b300c410e65), which modified the speed selection logic in the STM32 USB device controller driver.

I would like to highlight that this regression is addressed by the changes in this [PR](https://github.com/zephyrproject-rtos/zephyr/pull/89866). This update refactors the speed selection logic to more accurately consider both hardware support and device configuration, and resolves the USB malfunction observed on STM32F769i_disco.

**Test Result**

I have tested the fix using Zephyr OS build v4.2.0-2363-g4b00ef8171e4.
With the patch applied, the USB CDC ACM device is now working as expected on the STM32F769i_disco board. The device successfully enumerates, and data transfer is functional.

**Relevant log output:**

<img width="967" height="279" alt="Image" src="https://github.com/user-attachments/assets/c62e6ae3-8537-42f6-8ff5-84e97b51589d" />

Once merged, it should resolve the issue.

**Comment by ExtremeGTX** [comment]
Thanks @marwaiehm-st, I applied the patch you mentioned to my working tree and it improved the situation but still not like before, for example mass storage example still not working with protocol error messages. although it works on Raspberry Pi Pico.

Added this overlay file manually `stm32f769i_disco.overlay`
```
/ {
	msc_disk0 {
		compatible = "zephyr,flash-disk";
		partition = <&storage_partition>;
		disk-name = "NAND";
		cache-size = <4096>;
	};
};
```
Build
`west build -b stm32f769i_disco ./samples/subsys/usb/mass/ -DCONFIG_APP_MSC_STORAGE_FLASH_FATFS=y`
OR
`west build -b stm32f769i_disco ./samples/subsys/usb/mass/ -DEXTRA_DTC_OVERLAY_FILE="ramdisk.overlay" -DCONFIG_APP_MSC_STORAGE_RAM=y`

Logs
```
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.000,000] <inf> flash_stm32_qspi: qspi-nor-flash@0: SFDP v 1.6 AP ff with 3 PH
[00:00:00.000,000] <inf> flash_stm32_qspi: PH0: ff00 rev 1.6: 16 DW @ 30
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.000,000] <inf> flash_stm32_qspi: qspi-nor-flash@0: 64 MiBy flash
[00:00:00.000,000] <inf> flash_stm32_qspi: Flash - address mode: 4B
[00:00:00.000,000] <inf> flash_stm32_qspi: PH1: ffc2 rev 1.0: 4 DW @ 110
[00:00:00.000,000] <inf> flash_stm32_qspi: NOR quad-flash at 0x90000000 (0x4000000 bytes)
*** Booting Zephyr OS build v4.2.0-2294-g34b1e8a5f1c6 ***
Area 0 at 0x1a0000 on qspi-nor-flash@0 for 65011712 bytes
Mount /RAM:: 0
/RAM:: bsize = 512 ; frsize = 512 ; blocks = 158 ; bfree = 158
/RAM: opendir: 0
End of files
[00:00:00.062,000] <inf> main: The device is put in USB mass storage mode
[00:00:00.236,000] <inf> usbd_msc: Enable
[00:00:00.236,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:00.255,000] <wrn> udc: Spurious resume event
[00:00:00.255,000] <inf> usbd_msc: Disable
[00:00:00.255,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:00.307,000] <wrn> udc: Spurious resume event
[00:00:00.354,000] <inf> usbd_msc: Enable
[00:00:00.354,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:00.372,000] <wrn> udc: Spurious resume event
[00:00:00.372,000] <inf> usbd_msc: Disable
[00:00:00.372,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:00.422,000] <wrn> udc: Spurious resume event
[00:00:00.470,000] <inf> usbd_msc: Enable
[00:00:00.470,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:00.488,000] <wrn> udc: Spurious resume event
[00:00:00.488,000] <inf> usbd_msc: Disable
[00:00:00.488,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:00.538,000] <wrn> udc: Spurious resume event
[00:00:00.586,000] <inf> usbd_msc: Enable
[00:00:00.586,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:00.603,000] <wrn> udc: Spurious resume event
[00:00:00.603,000] <inf> usbd_msc: Disable
[00:00:00.603,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:00.655,000] <wrn> udc: Spurious resume event
[00:00:00.703,000] <inf> usbd_msc: Enable
[00:00:00.703,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:00.720,000] <wrn> udc: Spurious resume event
[00:00:00.720,000] <inf> usbd_msc: Disable
[00:00:00.720,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:00.771,000] <wrn> udc: Spurious resume event
[00:00:00.819,000] <inf> usbd_msc: Enable
[00:00:00.819,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:00.836,000] <wrn> udc: Spurious resume event
[00:00:00.836,000] <inf> usbd_msc: Disable
[00:00:00.836,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:00.887,000] <wrn> udc: Spurious resume event
[00:00:00.934,000] <inf> usbd_msc: Enable
[00:00:00.934,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:00.953,000] <wrn> udc: Spurious resume event
[00:00:00.953,000] <inf> usbd_msc: Disable
[00:00:00.953,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:01.002,000] <wrn> udc: Spurious resume event
.... keeps reporting these warnings forever ....
```

**Comment by marwaiehm-st** [comment]
Hi @ExtremeGTX ,

I have tested the mass storage example with the modifications introduced in the PR, and I can confirm that the previous error messages no longer appear. Based on my testing, the issue seems to be resolved with these changes.
`west build -b stm32f769i_disco ./samples/subsys/usb/mass/ -DEXTRA_DTC_OVERLAY_FILE="ramdisk.overlay" -DCONFIG_APP_MSC_STORAGE_RAM=y`

```shell
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.000,000] <inf> flash_stm32_qspi: qspi-nor-flash@0: SFDP v 1.6 AP ff with 3 PH
[00:00:00.000,000] <inf> flash_stm32_qspi: PH0: ff00 rev 1.6: 16 DW @ 30
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.000,000] <inf> flash_stm32_qspi: qspi-nor-flash@0: 64 MiBy flash
[00:00:00.000,000] <inf> flash_stm32_qspi: Flash - address mode: 4B
[00:00:00.000,000] <inf> flash_stm32_qspi: PH1: ffc2 rev 1.0: 4 DW @ 110
[00:00:00.000,000] <inf> flash_stm32_qspi: NOR quad-flash at 0x90000000 (0x4000000 bytes)
*** Booting Zephyr OS build v4.2.0-2363-g258c0a134a97 ***
Area 0 at 0x1a0000 on qspi-nor-flash@0 for 65011712 bytes
Mount /RAM:: 0
/RAM:: bsize = 512 ; frsize = 512 ; blocks = 158 ; bfree = 158
/RAM: opendir: 0
End of files
[00:00:00.062,000] <inf> main: The device is put in USB mass storage mode
[00:00:04.486,000] <wrn> udc: Spurious suspend event
[00:00:04.770,000] <wrn> udc: Spurious resume event
[00:00:04.844,000] <inf> usbd_msc: Enable
[00:00:04.844,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:05.954,000] <wrn> udc: Spurious resume event
[00:00:05.954,000] <inf> usbd_msc: Disable
[00:00:05.954,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:06.069,000] <wrn> udc: Spurious resume event
[00:00:06.141,000] <inf> usbd_msc: Enable
[00:00:06.141,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:06.204,000] <wrn> udc: Spurious resume event
[00:00:06.204,000] <inf> usbd_msc: Disable
[00:00:06.204,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:06.318,000] <wrn> udc: Spurious resume event
[00:00:06.390,000] <inf> usbd_msc: Enable
[00:00:06.390,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:06.453,000] <wrn> udc: Spurious resume event
[00:00:06.453,000] <inf> usbd_msc: Disable
[00:00:06.453,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:06.567,000] <wrn> udc: Spurious resume event
[00:00:06.639,000] <inf> usbd_msc: Enable
[00:00:06.639,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:06.702,000] <wrn> udc: Spurious resume event
[00:00:06.702,000] <inf> usbd_msc: Disable
[00:00:06.702,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:06.817,000] <wrn> udc: Spurious resume event
[00:00:06.889,000] <inf> usbd_msc: Enable
[00:00:06.889,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:06.952,000] <wrn> udc: Spurious resume event
[00:00:06.952,000] <inf> usbd_msc: Disable
[00:00:06.952,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:07.066,000] <wrn> udc: Spurious resume event
[00:00:07.138,000] <inf> usbd_msc: Enable
[00:00:07.138,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:07.201,000] <wrn> udc: Spurious resume event
[00:00:07.201,000] <inf> usbd_msc: Disable
[00:00:07.201,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:07.316,000] <wrn> udc: Spurious resume event
[00:00:07.388,000] <inf> usbd_msc: Enable
[00:00:07.388,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:07.443,000] <wrn> udc: Spurious resume event
[00:00:07.443,000] <inf> usbd_msc: Disable
[00:00:07.444,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:07.558,000] <wrn> udc: Spurious resume event
[00:00:07.630,000] <inf> usbd_msc: Enable
[00:00:07.630,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:07.693,000] <wrn> udc: Spurious resume event
[00:00:07.693,000] <inf> usbd_msc: Disable
[00:00:07.693,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:07.807,000] <wrn> udc: Spurious resume event
[00:00:07.879,000] <inf> usbd_msc: Enable
[00:00:07.879,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:07.942,000] <wrn> udc: Spurious resume event
[00:00:07.942,000] <inf> usbd_msc: Disable
[00:00:07.942,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:08.056,000] <wrn> udc: Spurious resume event
[00:00:08.128,000] <inf> usbd_msc: Enable
[00:00:08.128,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:08.191,000] <wrn> udc: Spurious resume event
[00:00:08.191,000] <inf> usbd_msc: Disable
[00:00:08.191,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:08.305,000] <wrn> udc: Spurious resume event
[00:00:08.377,000] <inf> usbd_msc: Enable
[00:00:08.377,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:08.440,000] <wrn> udc: Spurious resume event
[00:00:08.440,000] <inf> usbd_msc: Disable
[00:00:08.440,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:08.554,000] <wrn> udc: Spurious resume event
[00:00:08.626,000] <inf> usbd_msc: Enable
[00:00:08.626,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:08.689,000] <wrn> udc: Spurious resume event
[00:00:08.689,000] <inf> usbd_msc: Disable
[00:00:08.689,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:08.803,000] <wrn> udc: Spurious resume event
[00:00:08.875,000] <inf> usbd_msc: Enable
[00:00:08.875,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:08.932,000] <wrn> udc: Spurious resume event
[00:00:08.933,000] <inf> usbd_msc: Disable
[00:00:08.933,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:09.047,000] <wrn> udc: Spurious resume event
[00:00:09.119,000] <inf> usbd_msc: Enable
[00:00:09.119,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:09.182,000] <wrn> udc: Spurious resume event
[00:00:09.182,000] <inf> usbd_msc: Disable
[00:00:09.182,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:09.296,000] <wrn> udc: Spurious resume event
[00:00:09.368,000] <inf> usbd_msc: Enable
[00:00:09.368,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:09.431,000] <wrn> udc: Spurious resume event
[00:00:09.431,000] <inf> usbd_msc: Disable
[00:00:09.431,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:09.545,000] <wrn> udc: Spurious resume event
[00:00:09.617,000] <inf> usbd_msc: Enable
[00:00:09.617,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:09.680,000] <wrn> udc: Spurious resume event
[00:00:09.680,000] <inf> usbd_msc: Disable
[00:00:09.680,000] <wrn> usbd_msc: request ep 0x01, len 0 cancelled
[00:00:09.794,000] <wrn> udc: Spurious resume event
[00:00:09.866,000] <inf> usbd_msc: Enable
[00:00:09.866,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset


```

**Comment by ExtremeGTX** [comment]
Hi @marwaiehm-st 
I tried to build the same way as you shared but it didn't work, the mass storage volume is not displayed in Windows Explorer also i get the same logs as you shared non-stop `udc: Spurious resume event` followed by class enable/disable events which is not the case on non-ST platforms.

**Comment by mathieuchopstm** [comment]
No longer able to reproduce. CDC ACM sample is functional:
```
*** Booting Zephyr OS build v4.2.0-4812-g48a9b04885cb ***
[00:00:00.010,000] <inf> cdc_acm_echo: USB device support enabled
[00:00:00.010,000] <inf> cdc_acm_echo: Wait for DTR
[00:00:00.016,000] <inf> cdc_acm_echo: USBD message: Device suspended
[00:00:03.322,000] <inf> cdc_acm_echo: USBD message: Device suspended
[00:00:03.713,000] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:03.801,000] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:03.870,000] <inf> cdc_acm_echo: USBD message: New device configuration
[00:00:03.871,000] <inf> cdc_acm_echo: USBD message: CDC ACM line coding
[00:00:03.871,000] <inf> cdc_acm_echo: Baudrate 9600
[00:00:10.821,000] <inf> cdc_acm_echo: USBD message: CDC ACM control line state
[00:00:10.821,000] <inf> cdc_acm_echo: DTR set
[00:00:10.821,000] <inf> cdc_acm_echo: USBD message: CDC ACM line coding
[00:00:10.822,000] <inf> cdc_acm_echo: Baudrate 115200
[00:00:16.659,000] <inf> cdc_acm_echo: USBD message: CDC ACM control line state
[00:00:17.660,000] <inf> cdc_acm_echo: USBD message: CDC ACM control line state
[00:00:17.660,000] <inf> cdc_acm_echo: USBD message: CDC ACM line coding
[00:00:17.660,000] <inf> cdc_acm_echo: Baudrate 9600
[00:00:17.661,000] <inf> cdc_acm_echo: USBD message: CDC ACM control line state
```

USB mass is also somewhat functional, though there is a weird `LBA 0 is out of range` issue (which I think is not related to the driver). Creating a file on the RAMdisk MSC is functional however:
```
*** Booting Zephyr OS build v4.2.0-4812-g48a9b04885cb ***
Mount /RAM:: 0
/RAM:: bsize = 512 ; frsize = 512 ; blocks = 158 ; bfree = 158
/RAM: opendir: 0
End of files
[00:00:00.061,000] <inf> main: The device is put in USB mass storage mode
[00:00:00.535,000] <wrn> udc: Spurious resume event
[00:00:00.604,000] <inf> usbd_msc: Enable
[00:00:00.604,000] <inf> usbd_msc: Bulk-Only Mass Storage Reset
[00:00:01.659,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.664,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.667,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.668,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.669,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.670,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.672,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.674,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.675,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.675,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.676,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.677,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.678,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.680,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.681,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.682,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.683,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.684,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.685,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.686,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.686,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.687,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.688,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.689,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.713,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.714,000] <wrn> usbd_msc: LBA 0 is out of range
[00:00:01.720,000] <wrn> usbd_msc: LBA 0 is out of range
```

Please re-open issue if the problems persists.

**Comment by ExtremeGTX** [comment]
@mathieuchopstm comparing to commit zephyrproject-rtos/zephyr@1ea0267a315e31c81b125b27f3324f77e2a51cef things still not like before, I'm actively working on USB MTP Class https://github.com/zephyrproject-rtos/zephyr/pull/86832 and since the aformentioned commit, I can't get it to work.

Here is the logs when I try to transfer a file from device -> Host:

```
[00:00:14.990,000] <inf> usbd_ch9: Handle control 0x200277c4 ep 0x00, len 8, s:1 d:0 s:0
[00:00:14.990,000] <inf> usbd_ch9: protocol error:
[00:00:14.990,000] <inf> usbd_ch9: setup:
                                   21 64 00 00 00 00 06 00                          |!d......
[00:00:14.990,000] <inf> usbd_ch9: not supported
[00:00:14.990,000] <inf> usbd_ch9: Handle control 0x200277a0 ep 0x00, len 8, s:1 d:0 s:0
[00:00:14.990,000] <inf> usbd_ch9: protocol error:
[00:00:14.990,000] <inf> usbd_ch9: setup:
                                   a1 67 00 00 00 00 24 00                          |.g....$.
[00:00:14.990,000] <inf> usbd_ch9: not supported
[00:00:15.106,000] <inf> usbd_ch9: Handle control 0x200277e8 ep 0x00, len 8, s:1 d:0 s:0
[00:00:15.106,000] <inf> usbd_ch9: protocol error:
[00:00:15.106,000] <inf> usbd_ch9: setup:
                                   a1 67 00 00 00 00 24 00                          |.g....$.
[00:00:15.106,000] <inf> usbd_ch9: not supported
[00:00:15.215,000] <inf> usbd_ch9: Handle control 0x200277a0 ep 0x00, len 8, s:1 d:0 s:0
[00:00:15.215,000] <inf> usbd_ch9: protocol error:
[00:00:15.215,000] <inf> usbd_ch9: setup:
                                   a1 67 00 00 00 00 24 00                          |.g....$.
[00:00:15.215,000] <inf> usbd_ch9: not supported
[00:00:15.324,000] <inf> usbd_ch9: Handle control 0x200277e8 ep 0x00, len 8, s:1 d:0 s:0
[00:00:15.324,000] <inf> usbd_ch9: protocol error:
[00:00:15.324,000] <inf> usbd_ch9: setup:
                                   a1 67 00 00 00 00 24 00                          |.g....$.
[00:00:15.324,000] <inf> usbd_ch9: not supported
[00:00:15.434,000] <inf> usbd_ch9: Handle control 0x200277a0 ep 0x00, len 8, s:1 d:0 s:0
[00:00:15.434,000] <inf> usbd_ch9: protocol error:
[00:00:15.434,000] <inf> usbd_ch9: setup:
                                   a1 67 00 00 00 00 24 00                          |.g....$.
[00:00:15.434,000] <inf> usbd_ch9: not supported
[00:00:15.546,000] <inf> usbd_ch9: Handle control 0x200277e8 ep 0x00, len 8, s:1 d:0 s:0
[00:00:15.546,000] <inf> usbd_ch9: protocol error:
[00:00:15.546,000] <inf> usbd_ch9: setup:
                                   a1 67 00 00 00 00 24 00                          |.g....$.
```


I don't have deep experience with USB, but I tried to check if my implementation works on **RPi Pico** and it works, it doesn't report the same issues.

Thanks for looking into it.

**Comment by PeeJay** [comment]
Not sure if it's relevant but I have been having trouble with `<wrn> udc: Spurious resume event` on STM32G4. Enabling `CONFIG_UDC_DRIVER_LOG_LEVEL_ERR=y` remarkably fixes the error.

**Comment by ExtremeGTX** [comment]
```
[  725.386346] usb 2-1: new high-speed USB device number 7 using ehci-pci
[  725.634144] usb 2-1: New USB device found, idVendor=2fe3, idProduct=0008, bcdDevice= 4.03
[  725.634151] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  725.634153] usb 2-1: Product: USBD MSC sample
[  725.634155] usb 2-1: Manufacturer: Zephyr Project
[  725.634157] usb 2-1: SerialNumber: 33373330313851020023003B
[  725.639869] usb-storage 2-1:1.0: USB Mass Storage device detected
[  725.640512] scsi host33: usb-storage 2-1:1.0
[  726.678164] scsi 33:0:0:0: Direct-Access     Zephyr   FlashDisk        0.00 PQ: 0 ANSI: 4
[  726.679276] sd 33:0:0:0: Attached scsi generic sg3 type 0
[  726.690213] sd 33:0:0:0: [sdb] 126976 512-byte logical blocks: (65.0 MB/62.0 MiB)
[  726.696073] sd 33:0:0:0: [sdb] Write Protect is off
[  726.696098] sd 33:0:0:0: [sdb] Mode Sense: 03 00 00 00
[  726.703094] sd 33:0:0:0: [sdb] No Caching mode page found
[  726.703100] sd 33:0:0:0: [sdb] Assuming drive cache: write through
[  726.750119]  sdb:
[  726.750229] sd 33:0:0:0: [sdb] Attached SCSI removable disk
[  727.443486] FAT-fs (sdb): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[  765.751395] usb 2-1: reset high-speed USB device number 7 using ehci-pci
[  767.054058] kauditd_printk_skb: 146 callbacks suppressed
[  767.054061] audit: type=1400 audit(1768862934.974:158): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/cups/backend/cups-pdf" pid=5411 comm="apparmor_parser"
[  767.056835] audit: type=1400 audit(1768862934.977:159): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/sbin/cupsd" pid=5411 comm="apparmor_parser"
[  767.069624] audit: type=1400 audit(1768862934.989:160): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/sbin/cupsd//third_party" pid=5411 comm="apparmor_parser"
[  768.654654] audit: type=1400 audit(1768862936.584:161): apparmor="DENIED" operation="capable" class="cap" profile="/usr/sbin/cupsd" pid=5713 comm="cupsd" capability=12  capname="net_admin"
[  788.966570] workqueue: blk_mq_run_work_fn hogged CPU for >10000us 11 times, consider switching to WQ_UNBOUND
[  796.417189] usb 2-1: reset high-speed USB device number 7 using ehci-pci
[  813.369692] usb 2-1: reset high-speed USB device number 7 using ehci-pci
[  813.857561] usb 2-1: reset high-speed USB device number 7 using ehci-pci
[  824.622487] usb 2-1: reset high-speed USB device number 7 using ehci-pci
[  824.874867] sd 33:0:0:0: Device offlined - not ready after error recovery
[  824.874896] sd 33:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_ABORT driverbyte=DRIVER_OK cmd_age=89s
[  824.874914] sd 33:0:0:0: [sdb] tag#0 CDB: Write(10) 2a 00 00 00 00 68 00 00 f0 00
[  824.874917] I/O error, dev sdb, sector 104 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.874999] sd 33:0:0:0: rejecting I/O to offline device
[  824.875003] I/O error, dev sdb, sector 344 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.875086] I/O error, dev sdb, sector 584 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.875124] I/O error, dev sdb, sector 824 op 0x1:(WRITE) flags 0x4800 phys_seg 3 prio class 0
[  824.875135] I/O error, dev sdb, sector 1064 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.875143] I/O error, dev sdb, sector 1304 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.875151] I/O error, dev sdb, sector 1544 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.875159] I/O error, dev sdb, sector 1784 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.875167] I/O error, dev sdb, sector 2024 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.875174] I/O error, dev sdb, sector 2264 op 0x1:(WRITE) flags 0x4800 phys_seg 2 prio class 0
[  824.875511] Buffer I/O error on dev sdb, logical block 1, lost async page write
[  824.875536] Buffer I/O error on dev sdb, logical block 2, lost async page write
[  824.875538] Buffer I/O error on dev sdb, logical block 3, lost async page write
[  824.875539] Buffer I/O error on dev sdb, logical block 4, lost async page write
[  824.875541] Buffer I/O error on dev sdb, logical block 5, lost async page write
[  824.875542] Buffer I/O error on dev sdb, logical block 6, lost async page write
[  824.875763] Buffer I/O error on dev sdb, logical block 64, lost async page write
[  825.011763] FAT-fs (sdb): Directory bread(block 64) failed
[  825.011820] FAT-fs (sdb): Directory bread(block 64) failed
[  855.768963] blk_print_req_error: 45 callbacks suppressed
[  855.768966] I/O error, dev sdb, sector 64 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  855.768978] FAT-fs (sdb): unable to read inode block for updating (i_pos 1028)
```

I tried again, it mounts successfully on Linux, but on Windows "Explorer" keeps loading forever.
On Linux, I tried to copy a big file and as you see I got a lot of I/O error, but I'm not sure now if it is STM32 UDC Driver or something else, if you think it is irrelevant, feel free to close the Bug.

Thanks for your help.
